### ISSUE TITLE
Sesame protocol does not work over POST?

### ISSUE THREAD

**Issue by pumba-lt** [dydra/support#12]
I hope I got all the encodings correctly, but I think this illustrates that currently the Sesame protocol implementation does not support `application/x-www-form-urlencoded` `POST` requests.

```
curl -d @sesame.txt -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/sparql-results+xml" "http://graphity.dydra.com/graphity/sesame-protocol-test/sparql"
```
Contents of sesame.txt:
```
query=SELECT+*+%7B+GRAPH+%3Fg+%7B+%3Fs+%3Fp+%3Fo+%7D+%7D&%24s=%3Chttp%3A%2F%2Flocalhost%2F%3E
```

Result bindings for `?s` include `http://remote/`, while in my opinion there should only be `http://localhost/`.
Looks like the query arguments are not read from `POST` request body.

**Comment by bendiken** [comment]
Supplying query variable bindings inside an `application/x-www-form-urlencoded` body is not supported. The bindings must be provided as URL query parameters.

Note that we do not purport to implement the Sesame HTTP protocol as such (in general, it has been supplanted by the Graph Store Protocol).

Rather, we provide support for query variable bindings over HTTP, patterned after how the Sesame HTTP protocol initially pioneered support for them. We have no current plans to extend that to include the `application/x-www-form-urlencoded` form.

**Comment by pumba-lt** [comment]
Well, then we have a problem... Our use case is not related to stored queries. Our motivation is to increase performance by avoiding query re-compilation. When James pointed me to the Sesame protocol, I started implementing it.

Jena accepts "request parameters" for SPARQL HTTP requests. It chooses the request method based on querystring size. Which means the parameters end up either in the `GET` URL query string, or in the `POST` request body. There is no method to set URL query parameters for `POST`.

I think Dydra's current behavior is inconsistent both with the Sesame protocol and the SPARQL protocol:
http://rdf4j.org/sesame/2.7/docs/system.docbook?view#repository-queries
http://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#query-via-post-urlencoded

**Comment by lisp** [comment]
the sparql protocol can govern only those parameters which it specifies.
note also please, the earlier response wrt to sesame conformance.
perhaps, as an alternative, perhaps there would be a way to circumvent the deficiency in the jena api?

**Comment by pumba-lt** [comment]
Of course, SPARQL protocol governs only its own parameters. But it also shows the *method* for passing parameters, as in request body vs. URL. Why should it differ for non-standard parameters? I think you also agreed that request body parameter would be the reasonable thing here.

Anyway, I guess I will have to dig into Jena's internals. Suddenly it looks like much more work than anticipated for a seemingly simple feature..

**Comment by bendiken** [comment]
@pumba-lt You're right that consistency is good. We've now changed the handling of bindings to support also those specified in `application/x-www-form-urlencoded` bodies.
