### ISSUE TITLE
Join with SERVICE returns no results

### ISSUE THREAD

**Issue by pumba-lt** [dydra/support#13]
Results for `?class` include `http://graphityhq.com/gh#Space`:
http://graphity.dydra.com/graphity/homepage-auth-test/query#select

If I add a `SERVICE` sub-pattern with `?class`, no results are returned:
http://graphity.dydra.com/graphity/homepage-auth-test/query#select-service

However, the same sub-pattern as `SELECT` on the respective endpoint return results that include `http://graphityhq.com/gh#Space` for `?class`:
http://graphity.dydra.com/graphity/homepage-test/query#selectclass

**Comment by lisp** [comment]
from your examples, it appears that you expect the query

SELECT *
{ SERVICE <http://graphity.dydra.com/graphity/homepage-test/sparql>
  {   { <http://localhost:8080/graphity-homepage/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?class }
      UNION
      { GRAPH ?g
        { <http://localhost:8080/graphity-homepage/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?class }
      }
  }
}

(see http://graphity.dydra.com/graphity/homepage-auth-test/query#service-to-homepage-test)
applied to the endpoint for "http://graphity.dydra.com/graphity/homepage-auth-test” to return the same results as 

SELECT *
{   { <http://localhost:8080/graphity-homepage/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?class }
      UNION
      { GRAPH ?g
        { <http://localhost:8080/graphity-homepage/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?class }
      }
  }

(see http://graphity.dydra.com/graphity/homepage-test/query#select-at-homepage-test)
applied to the endpoint for "http://graphity.dydra.com/graphity/homepage-test/sparql”

so far as i can tell, they do:

?class	?g
http://xmlns.com/foaf/0.1/Document	http://localhost:8080/graphity-homepage/graphs/
http://rdfs.org/sioc/ns#Site	http://localhost:8080/graphity-homepage/graphs/
http://graphityhq.com/gh#Space	http://localhost:8080/graphity-homepage/graphs/

**Comment by lisp** [comment]
or does your issue arise due to the scope of the graph form, as indicated by a depiction of the concrete query:      

    (ORG.DATAGRAPH.SPOCQ.EVALUATION:PROJECT
       (ORG.DATAGRAPH.SPOCQ.EVALUATION:JOIN
        (ORG.DATAGRAPH.SPOCQ.EVALUATION::SERVICE
         <http://graphity.dydra.com/graphity/homepage-test/sparql>
         '(select
           (union
            (bgp
              (graph ?::aclGraph)
              (triple <http://localhost:8080/graphity-homepage/>
                      |http://www.w3.org/1999/02/22-rdf-syntax-ns#|:type ?::class))
            (graph ?::g
                   (bgp
                     (triple <http://localhost:8080/graphity-homepage/>
                             |http://www.w3.org/1999/02/22-rdf-syntax-ns#|:type
                             ?::class))))
           (?::aclGraph ?::class ?::g)))
        (agp (graph ?::aclGraph) (id #:AGP-7477)
         (declare (opaque ?::aclGraph ?::auth ?::class))
         (triple ?::auth |http://www.w3.org/ns/auth/acl#|:accessToClass ?::class)))
       '(?::aclGraph ?::auth ?::class ?::g))

**Comment by pumba-lt** [comment]
Yes I think it is related to `GRAPH`. I've made a simplified version:
http://graphity.dydra.com/graphity/homepage-auth-test/query#select-service
Simple pattern joined with `SERVICE` produces no results. Separately, each of them produces `http://graphityhq.com/gh#Space` as `?class`.

**Comment by lisp** [comment]
i had already made a query for you,

    http://graphity.dydra.com/graphity/homepage-auth-test/query#select-service-with-clear-scope

which i expect may better express your intent.

**Comment by pumba-lt** [comment]
Thanks. Indeed it does. I was hoping to simplify the query by wrapping it all within `GRAPH ?aclGraph`, but it looks like the old version which repeats it in multiple patterns was correct.
