### ISSUE TITLE
ASK with SERVICE returns different result with Sesame bindings

### ISSUE THREAD

**Issue by pumba-lt** [dydra/support#14]
I'm lost as to how to reproduce this as a minimal case, mostly because of `SERVICE` at play. But I think this shows the difference in results.

`ASK` with inlined bindings returns `false`:
http://graphity.dydra.com/graphity/homepage-auth-test/query#askbound

The same query with remote bindings `( ?agent, <http://xmlns.com/foaf/0.1/Agent> )( ?this, <http://localhost:8080/graphity-homepage/persons> )( ?mode, <http://www.w3.org/ns/auth/acl#Read> )` returns `true`:
```
curl -H "Accept: application/sparql-results+xml" "http://graphity.dydra.com/graphity/homepage-auth-test/sparql?query=PREFIX++foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX++acl%3A++%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23%3E%0A%0AASK%0AWHERE%0A++%7B+++%7B+GRAPH+%3FaclGraph%0A++++++++++%7B+%3Fauth+acl%3Amode+%3Fmode+.%0A++++++++++++%3Fauth+acl%3AaccessTo+%3Fthis%0A++++++++++%7D%0A++++++%7D%0A++++UNION%0A++++++%7B+SERVICE+%3Chttp%3A%2F%2Fgraphity.dydra.com%2Fgraphity%2Fhomepage-test%2Fsparql%3E%0A++++++++++%7B+++%7B+%3Fthis+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+%3Fclass+%7D%0A++++++++++++UNION%0A++++++++++++++%7B+GRAPH+%3Fg%0A++++++++++++++++++%7B+%3Fthis+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+%3Fclass+%7D%0A++++++++++++++%7D%0A++++++++++%7D%0A++++++++GRAPH+%3FaclGraph%0A++++++++++%7B+%3Fauth+acl%3Amode+%3Fmode+.%0A++++++++++++%3Fauth+acl%3AaccessToClass+%3Fclass%0A++++++++++%7D%0A++++++%7D%0A++++GRAPH+%3FaclGraph%0A++++++%7B+++%7B+%3Fauth+acl%3AagentClass+foaf%3AAgent+%7D%0A++++++++UNION%0A++++++++++%7B+%3Fauth+acl%3Aagent+%3Fagent+%7D%0A++++++++UNION%0A++++++++++%7B+%3Fauth+acl%3AagentClass+%3FagentClass%0A++++++++++++GRAPH+%3FagentGraph%0A++++++++++++++%7B+%3Fagent+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+%3FagentClass+%7D%0A++++++++++%7D%0A++++++%7D%0A++%7D%0A&%24agent=%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FAgent%3E&%24mode=%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23Read%3E&%24this=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-homepage%2Fpersons%3E"
```

**Comment by pumba-lt** [comment]
On a repository with 1 triple repository:

`ASK` query returns `true`:
http://graphity.dydra.com/graphity/sesame-protocol-auth-test/query#askunbound

When variable `?this` is bound to `<http://localhost:8080/graphity-homepage/persons>`, the query returns `false`:
http://graphity.dydra.com/graphity/sesame-protocol-auth-test/query#askbound

However, the same query with same binding over remote protocol returns `true`:
```
curl -H "Accept: application/sparql-results+xml" "http://graphity.dydra.com/graphity/sesame-protocol-auth-test/sparql?query=PREFIX%20%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20%20acl%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23%3E%0A%0AASK%0A%7B%20SERVICE%20%3Chttp%3A%2F%2Fgraphity.dydra.com%2Fgraphity%2Fhomepage-test%2Fsparql%3E%0A%20%20%20%20%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20GRAPH%20%3Fg%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20%3Fthis%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E%20%3Fclass%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20GRAPH%20%3FaclGraph%0A%20%20%20%20%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Fauth%20acl%3AaccessToClass%20%3Fclass%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%7D%0A&%24this=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-homepage%2Fpersons%3E"
```

**Comment by lisp** [comment]
your recent site upgrade to support query arguments required a patch to limit the verbosity of the frequent errors due to invalid service requests. unfortunately, one of these also limited the scope of the bindings to exclude service clauses. that has been corrected.

    curl -H "Accept: application/sparql-results+xml" "http://graphity.dydra.com/graphity/sesame-protocol-auth-test/sparql?query=PREFIX%20%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20%20acl%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23%3E%0A%0AASK%0A%7B%20SERVICE%20%3Chttp%3A%2F%2Fgraphity.dydra.com%2Fgraphity%2Fhomepage-test%2Fsparql%3E%0A%20%20%20%20%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20GRAPH%20%3Fg%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20%3Fthis%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E%20%3Fclass%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20GRAPH%20%3FaclGraph%0A%20%20%20%20%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Fauth%20acl%3AaccessToClass%20%3Fclass%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%7D%0A&%24this=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-homepage%2Fpersons%3E"
    <?xml version="1.0" encoding="UTF-8"?>
    <sparql xmlns="http://www.w3.org/2005/sparql-results#">
      <head/>
      <boolean>false</boolean>
    </sparql>
