### ISSUE TITLE
Support for COPY and MOVE graphs

### ISSUE THREAD

**Issue by ColinMaudry** [dydra/support#16]
On http://dydra.com/colin-maudry/datagouvfr, in order to improve the availability of the data on my repo, I would like to do the post-processing SPARQL operations on a temporary graph.

I consequently thought of doing the following:
1. PUT to temp graph
2. Do post-processing on temp graph
3. MOVE temp graph to production graph (or DROP production graph and MOVE temp graph if MOVE doesn't overwrite the existing graph).

I was able to use CREATE GRAPH and DROP GRAPH.

COPY doesn't do much: [I try to COPY](http://dydra.com/colin-maudry/datagouvfr/query#test-copy), I don't get errors (returns "true") but [no new graph](http://dydra.com/colin-maudry/datagouvfr/query#list-graphs).

[MOVE returns an error](http://dydra.com/colin-maudry/datagouvfr/query#test-move) (Query Load Failed, a is null).

So what's up with the support of COPY and MOVE graphs?

**Comment by lisp** [comment]
for internal reference: spocq#211

**Comment by ColinMaudry** [comment]
Any progress on this issue?

MOVE still returns the same error on http://dydra.com/colin-maudry/datagouvfr/query.

Thanks.

**Comment by lisp** [comment]
resolved. see https://github.com/dydra/http-api-tests/blob/master/sparql-protocol/POST-move-graph.sh
