### ISSUE TITLE
Query fails after adding VALUES

### ISSUE THREAD

**Issue by namedgraph** [dydra/support#18]
http://graphity.dydra.com/graphity/homepage-test/query#values

```
Query Load Failed

An unspecified internal server error was encountered
```

At least according to sparql.org, it's valid.

**Comment by namedgraph** [comment]
The same situation with `FILTER IN`? I'm probably overlooking something, but still it looks valid:
http://graphity.dydra.com/graphity/homepage-test/query#filterin

**Comment by lisp** [comment]
for future reference, what did you think was off and what was the actual issue?

**Comment by namedgraph** [comment]
My mistake - `SERVICE` values were not bound... I don't know why Jena's validator allows that.

**Comment by lisp** [comment]
it would also be worthwhile to include the query text at issue, rather than just a link, as the resource at the other end of the link is likely to vary.
that would also have the likely beneficial side-effect, to reduce the query to the actual issue at hand and avoid ambiguous causes.

**Comment by namedgraph** [comment]
Yes you are right of course. However quite a bit of work went into making these queries work as they do, so I would prefer to keep them private if possible. And with the link, I can control that.

**Comment by lisp** [comment]
in that case, the second aspect, to edit the query down to the salient issue, would provide two-fold benefit.
