### ISSUE TITLE
Different results with different HTTP methods

### ISSUE THREAD

**Issue by namedgraph** [dydra/support#20]
```
curl -X POST -d @describe-this.rq -H "Accept: application/n-triples" -H "Content-Type: application/sparql-query" "http://graphity.dydra.com/graphity/graphity-platform-test/sparql?%24agent=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2Facl%2Fpersons%2FMartynas%2520Jusevi%25C4%258Dius%23this%3E&%24this=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E&user_id=-131480624&%24baseUri=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E"
```

returns 44 triples (as expected). The same query with the same bindings over `GET` returns only 23 triples:

```
curl -H "Accept: application/n-triples" "http://graphity.dydra.com/graphity/graphity-platform-test/sparql?query=BASE++++%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E%0APREFIX++describeForm%3A+%3Curn%3Adydra%3Asimple-concise-bounded-description%3E%0APREFIX++describeSubjectDepth%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23_4%3E%0A%0ADESCRIBE+%3Fthis+%3Fdoc+%3Fthing%0AWHERE%0A++%7B+++%7B+GRAPH+%3Fgraph%0A++++++++++%7B+%3Fthis+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FDocument%3E%0A++++++++++++OPTIONAL%0A++++++++++++++%7B+%3Fthis+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FprimaryTopic%3E+%3Fthing+%7D%0A++++++++++%7D%0A++++++%7D%0A++++UNION%0A++++++%7B+%7B+SELECT+DISTINCT++%3Fdoc+%3Fthing%0A++++++++++WHERE%0A++++++++++++%7B+GRAPH+%3FchildGraph%0A++++++++++++++++%7B+++%7B+%3Fdoc+%3Chttp%3A%2F%2Frdfs.org%2Fsioc%2Fns%23has_space%3E+%3Fthis+%7D%0A++++++++++++++++++UNION%0A++++++++++++++++++++%7B+%3Fdoc+%3Chttp%3A%2F%2Frdfs.org%2Fsioc%2Fns%23has_parent%3E+%3Fthis+%7D%0A++++++++++++++++++UNION%0A++++++++++++++++++++%7B+%3Fdoc+%3Chttp%3A%2F%2Frdfs.org%2Fsioc%2Fns%23has_container%3E+%3Fthis+%7D%0A++++++++++++++++++OPTIONAL%0A++++++++++++++++++++%7B+%3Fdoc+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FprimaryTopic%3E+%3Fthing+%7D%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++++OFFSET++0%0A++++++++++LIMIT+++20%0A++++++++%7D%0A++++++%7D%0A++%7D%0A&%24agent=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2Facl%2Fpersons%2FMartynas%2520Jusevi%25C4%258Dius%23this%3E&%24this=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E&user_id=-131480624&%24baseUri=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E"
```

`describe-this.rq`:

```
BASE    <http://localhost:8080/graphity-platform/>
PREFIX  describeForm: <urn:dydra:simple-concise-bounded-description>
PREFIX  describeSubjectDepth: <http://www.w3.org/1999/02/22-rdf-syntax-ns#_4>

DESCRIBE ?this ?doc ?thing
WHERE
  {   { GRAPH ?graph
          { ?this <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Document>
            OPTIONAL
              { ?this <http://xmlns.com/foaf/0.1/primaryTopic> ?thing }
          }
      }
    UNION
      { { SELECT DISTINCT  ?doc ?thing
          WHERE
            { GRAPH ?childGraph
                {   { ?doc <http://rdfs.org/sioc/ns#has_space> ?this }
                  UNION
                    { ?doc <http://rdfs.org/sioc/ns#has_parent> ?this }
                  UNION
                    { ?doc <http://rdfs.org/sioc/ns#has_container> ?this }
                  OPTIONAL
                    { ?doc <http://xmlns.com/foaf/0.1/primaryTopic> ?thing }
                }
            }
          OFFSET  0
          LIMIT   20
        }
      }
  }
```

**Comment by lisp** [comment]
based on the description, above, i was not able to reproduce the reported behavior.
at the present time, both mode yield forty-four solutions:

berlin:cases jamesanderson$ curl  -H "Accept: application/n-triples" -X POST -d @describe-this.rq -H "Content-Type: application/sparql-query" "http://graphity.dydra.com/graphity/graphity-platform-test/sparql?&%24agent=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2Facl%2Fpersons%2FMartynas%2520Jusevi%25C4%258Dius%23this%3E&%24this=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E&user_id=-131480624&%24baseUri=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E" | tee github-20-as-post.nt | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6592    0  5589  100  1003  10690   1918 --:--:-- --:--:-- --:--:-- 10706
      44     185    5589
berlin:cases jamesanderson$ curl -H "Accept: application/n-triples" "http://graphity.dydra.com/graphity/graphity-platform-test/sparql?query=BASE++++%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E%0APREFIX++describeForm%3A+%3Curn%3Adydra%3Asimple-concise-bounded-description%3E%0APREFIX++describeSubjectDepth%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23_4%3E%0A%0ADESCRIBE+%3Fthis+%3Fdoc+%3Fthing%0AWHERE%0A++%7B+++%7B+GRAPH+%3Fgraph%0A++++++++++%7B+%3Fthis+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FDocument%3E%0A++++++++++++OPTIONAL%0A++++++++++++++%7B+%3Fthis+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FprimaryTopic%3E+%3Fthing+%7D%0A++++++++++%7D%0A++++++%7D%0A++++UNION%0A++++++%7B+%7B+SELECT+DISTINCT++%3Fdoc+%3Fthing%0A++++++++++WHERE%0A++++++++++++%7B+GRAPH+%3FchildGraph%0A++++++++++++++++%7B+++%7B+%3Fdoc+%3Chttp%3A%2F%2Frdfs.org%2Fsioc%2Fns%23has_space%3E+%3Fthis+%7D%0A++++++++++++++++++UNION%0A++++++++++++++++++++%7B+%3Fdoc+%3Chttp%3A%2F%2Frdfs.org%2Fsioc%2Fns%23has_parent%3E+%3Fthis+%7D%0A++++++++++++++++++UNION%0A++++++++++++++++++++%7B+%3Fdoc+%3Chttp%3A%2F%2Frdfs.org%2Fsioc%2Fns%23has_container%3E+%3Fthis+%7D%0A++++++++++++++++++OPTIONAL%0A++++++++++++++++++++%7B+%3Fdoc+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FprimaryTopic%3E+%3Fthing+%7D%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++++OFFSET++0%0A++++++++++LIMIT+++20%0A++++++++%7D%0A++++++%7D%0A++%7D%0A&%24agent=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2Facl%2Fpersons%2FMartynas%2520Jusevi%25C4%258Dius%23this%3E&%24this=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E&user_id=-131480624&%24baseUri=%3Chttp%3A%2F%2Flocalhost%3A8080%2Fgraphity-platform%2F%3E" | tee github-20-as-get.nt | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5589    0  5589    0     0  12807      0 --:--:-- --:--:-- --:--:-- 12818
      44     185    5589
berlin:cases jamesanderson$ diff github-20-as-
github-20-as-get.nt   github-20-as-post.nt  
berlin:cases jamesanderson$ diff github-20-as-*
berlin:cases jamesanderson$

**Comment by namedgraph** [comment]
Yes now I also get the correct result. Arto, did you observe the difference though?
Maybe this could do with caching? I noticed this soon after importing a new dataset.

**Comment by artob** [comment]
@pumba-lt no, sorry, I couldn't reproduce it either. If it should reoccur, please capture the outputs as well, that might contain some clue.

**Comment by lisp** [comment]
if it was a specific sequence of operations which yielded these divergent results, the best way to capture them would be a script which starts with a repository with readily enumerable content and goes through the steps to reproduce the results.
