### ISSUE TITLE
Graph Store Protocol DELETE returns a 500

### ISSUE THREAD

**Issue by namedgraph** [dydra/support#21]
`DELETE` on a graph gives 500 error (`Authorization` removed):
`curl -X DELETE "http://graphity.dydra.com/graphity/refrigeration-stock-test/service?graph=http%3A%2F%2Flocalhost%3A8080%2Fref-stock%2Fgraphs%2FDanfoss%252520ball%252520valves%252520GBC%252520renamed.xlsx"`

**Comment by artob** [comment]
This was a regression bug, sorry about that. Now remedied on your host.
