### ISSUE TITLE
DESCRIBE does not (always) include blank node closure

### ISSUE THREAD

**Issue by namedgraph** [dydra/support#22]
```
PREFIX  describeSubjectDepth: <http://www.w3.org/1999/02/22-rdf-syntax-ns#_4>

DESCRIBE <http://localhost:8080/graphity-homepage/events/34187320-9fc8-11e3-a5e2-0800200c9a66#this>
```

http://graphity.dydra.com/graphity/describe-test/query#describeevent-4

**Comment by lisp** [comment]
the initial query behaved as intended, but subsequent identical requests are served from a cloned version, which neglects to recognize pragmas from the prototype.

**Comment by lisp** [comment]
we have released a correction to graphity. please check the behavior.
