### ISSUE TITLE
Leading fractional zeros dropped from xsd:decimal values

### ISSUE THREAD

**Issue by knoan** [dydra/support#29]
Values like `1.01` get stored as `1.1`. To reproduce:

```
insert data {
    <test:x> <test:p>
        "1.1"^^<http://www.w3.org/2001/XMLSchema#decimal>,
        "1.02"^^<http://www.w3.org/2001/XMLSchema#decimal>,
        "1.003"^^<http://www.w3.org/2001/XMLSchema#decimal>,
         1.4,
         1.05,
         1.006,
        "1.7"^^<http://www.w3.org/2001/XMLSchema#float>,
        "1.08"^^<http://www.w3.org/2001/XMLSchema#float>,
        "1.009"^^<http://www.w3.org/2001/XMLSchema#float>
}
```

`select ?o { ?s ?p ?o }` yields:

```
1.4
1.1
1.08E0
1.7E0
1.2
1.3
1.5
1.6
1.009E0
```

`xsd:decimal` is affected in both notations, while `xsd:float` seems to be handled correctly.

Dumping the repository yields the same results.

**Comment by artob** [comment]
We have triaged the `xsd:decimal` regression and expect to deploy a fix soon.

**Comment by artob** [comment]
This regression has been resolved and the correction deployed to dydra.com today.

Note that any dataset that was affected (i.e.,, wherein decimal literals were incorrectly parsed on import) would need to be reloaded from its origin data files, at which point the values will now be parsed correctly.
