### ISSUE TITLE
LOAD SILENT gives an error

### ISSUE THREAD

**Issue by jaw111** [dydra/support#3]
When I try to do a `LOAD SILENT` operation on public dydra.com then I get an error:

> Query Load Failed
> An unspecified internal server error was encountered

An example operation is:

    LOAD SILENT <http://dbpedia.org/resource/Berlin> INTO GRAPH <http://dbpedia.org/resource/Berlin>

This is a valid operation according to the SPARQL 1.1 Update specification for `LOAD`: http://www.w3.org/TR/sparql11-update/#load

**Comment by lisp** [comment]
resolved in the 2015-07-14 release.
