### ISSUE TITLE
regex() fails to match literals bound to variables

### ISSUE THREAD

**Issue by knoan** [dydra/support#30]
The following unexpectedly return `false`.

```
ask { bind ('test literal' as ?l) filter (regex(?l, 'test')) } 
```

Returns `true` as expected if either i) the literal is passed directly to `regex()` or ii) the variable is explicitly cast to a string.

```
  ask { filter (regex('test literal', 'test')) }
  ask { bind ('test literal' as ?l) filter (regex(str(?l), 'test')) }
```

**Comment by lisp** [comment]
resolved and recorded as

   https://github.com/dydra/http-api-tests/blob/master/sparql-protocol/regex/GET-regex-srj.sh
