### ISSUE TITLE
ceil() increases integral values

### ISSUE THREAD

**Issue by knoan** [dydra/support#32]
I'd expect the following to return `49`, while the actual value is `50`.

```
select (ceil(49.0) as ?value) {}
```

**Comment by lisp** [comment]
as would i.
it appears, that the language run-time miscomputes the value for unit rationals - that is denominator 1, but also numerator 0,
will need to add logic to compensate.

**Comment by lisp** [comment]
the upstream bug and patch ( https://bugs.launchpad.net/sbcl/+bug/1488552 ) was rejected as "invalid". fortunately, the run-time does not share that reviewer's opinion and we will be able to patch the truncate implementation locally to resolve this issue.

**Comment by artob** [comment]
We have resolved this issue on [dydra.com](http://dydra.com) as of today.
