### ISSUE TITLE
Add direct links to views on a repository homepage

### ISSUE THREAD

**Issue by jaw111** [dydra/support#4]
On a repository homepage (e.g. http://dydra.com/bendiken/foaf) the list of views currently links through to the query editor (e.g. http://dydra.com/bendiken/foaf/query#all-data) from where you can open the view (http://dydra.com/bendiken/foaf/all-data.html).

It would be nice to have a link direct to the view from the repository homepage.

**Comment by lisp** [comment]
look again.

**Comment by jaw111** [comment]
excellent, thanks!
