### ISSUE TITLE
POSTing statements always fail with 401 Unauthorized

### ISSUE THREAD

**Issue by pduchesne** [dydra/support#40]
Trying to add statements to a repository, i always get an HTTP 401, both when using token in the request

> POST http://dydra.com/johndoe/repositories/myrepo/statements?auth_token=MYTOKEN HTTP/1.1
> 
> 401 Unauthorized

or with Basic Authentication

> POST http://dydra.com/johndoe/repositories/myrepo/statements HTTP/1.1
> Authorization: Basic xxxx
> 
> 401 Unauthorized

**Comment by lisp** [comment]
so far as i can see, your application issues get and put requests with an auth token, but no post request today appears to have one.
could it be, that the interaction model is expecting to get the challenge and then respond with the token?

**Comment by pduchesne** [comment]
well, what i'm initially trying to do is to connect using the java
Sesame HTTPRepository , and that resulted in 401 responses. It think it
uses Basic authentication with a challenge, but I didn't debug much inside
it.

So I tried to reproduce the problem doing HTTP POSTs myself, and observed
the behaviour described above.

More specifically :

This doesn't work, as expected (my repo is private) :

> curl -X GET http://dydra.com/pduchesne/repositories/playground/statements

This works (adding the user/password) :

> curl -X GET http://dydra.com/pduchesne/repositories/playground/statements -u 'USER:PASS'

But this doesn't :

> curl -X POST http://dydra.com/pduchesne/repositories/playground/statements --data-binary "@/statementsFile.ttl" -u 'USER:PASS'

Thank you.

**Comment by lisp** [comment]
use the graph store protocol instead.
i attach an example file which covers the various operations.
[example.txt](https://github.com/dydra/support/files/105709/example.txt)

**Comment by pduchesne** [comment]
yes, it works using that protocol.
Thank you.

**Comment by lisp** [comment]
nice, that it works for your case.
we do recommend the gsp over sesame whenever possible
the latter has seen no users for years and, were it to be required, our experience with vocbench indicated that we would have to emulate sesame's transaction management over http in order for write to work.
this limits it to read-only, as we would not recommend that approach for remote requests.
