### ISSUE TITLE
Literals resembling compact IRIs casted as compact IRIs

### ISSUE THREAD

**Issue by jindrichmynarz** [dydra/support#46]
When you have a literal resembling a compact IRI, such as `"abc:def"`, it is casted as compact IRI. 

Query:

``` sparql
SELECT ("abc:def" AS ?ex) WHERE {}
```

Error:

```
client error: Condition: While processing, an error was signaled: Unbound prefix: 'abc'.
failed to parse after 'abc'.
SELECT ("abc:def" AS ?ex) WHERE {}
.
```

More realistic example of rewriting HTTP IRIs to HTTPS:

``` sparql
(IRI(REPLACE(STR(?httpIri), "^http:", "https:")) AS ?httpsIri)
```

Tested using the web query console of Dydra.

**Comment by lisp** [comment]
yes, this is a known bug.
if it is blocking you, we have a patch for it.

> Tested using the web query console of Dydra.

please save the query and send a link so - if you need the patch, we can verify the result with your actual use-case.

**Comment by jindrichmynarz** [comment]
Actually, the view of the saved query swallows the error and presents empty results instead: http://dydra.com/jindrichmynarz/sparqlab/curie-like-literals.html

**Comment by lisp** [comment]
from the view, i found the query text. it is a very simple case which should now work.
please let us know if more complicated formulations cause any problems.

**Comment by jindrichmynarz** [comment]
The issue is now resolved.
