### ISSUE TITLE
Fail to log in using commandline rubygem

### ISSUE THREAD

**Issue by ubindr** [dydra/support#47]
Using the rubygem dydra tool, I'm unable to login to the service. 

> dydra create test-1-2-3
> Email or username:...
> Password:...
> User ... not found

Username and password supplied are identical to the one's used to login on the website.
Login on the website works fine.

My computer:
Ubuntu 16.04 - Kernel: 4.4.0-36 x86_64
Ruby v: 2.3

**Comment by lisp** [comment]
we had neglected to decommission that gem, but have now done so, as our development path has moved away from support for remote command-line operations.

if you have available a means for direct contact, we can discuss with you the available alternatives.

**Comment by ubindr** [comment]
Thanks for the response. Using the web interface to upload data and do some basic querying. Just to verify my coding efforts ;).

**Comment by lisp** [comment]
the web interface is the most convenient way to develop and test queries.
once you have them in place, production work is then via the graph strore and/or sparql protocols, with the option to use the saved queries as views.
