### ISSUE TITLE
Value clause not visible to filter exists / not exists

### ISSUE THREAD

**Issue by knoan** [dydra/support#48]
The bindings provide by the values clause in the following query don't appear to be available to the pattern inside `filter not exists`.

Same behaviour tested on a populated repository for `filter exists`  patterns.

Works as expected on RDF4J 2.0 Native Store and Ontotext GraphDB 7.0.

Works as expected if the `value` clause is moved inside the main select.

```
select ?value { 

    filter not exists { ?value a <test:Class> } 

} values ?value {

    <test:value>

}
```

Expected: `?value = <test:value>`
Actual: empty result set

**Comment by lisp** [comment]
please save the query among the views for some repositroy and include a link here.

note that you expressed query is not the same as

select ?value { 
  values ?value {  test:value }
  filter not exists { ?value a test:Class } 
}

sparql.org yields the following form for your query when parsed.

```
  1 (base <http://example/base/>
  2   (project (?value)
  3     (join
  4       (filter (notexists (bgp (triple ?value <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <test:Class>)))
  5         (table unit))
  6       (table (vars ?value)
  7         (row [?value <test:value>])
  8       ))))
```

it agrees on an abstract level with our parse.
should that be expected to yield your indicated result?

**Comment by knoan** [comment]
> please save the query among the views for some repositroy and include a link here.

http://dydra.com/metreeca/test/issue-48.html

> it agrees on an abstract level with our parse.
> should that be expected to yield your indicated result?

Probably not :( the actual results are consistent with the abstract plan.
Inconsistent results likely due to bugs on other backends…
