### ISSUE TITLE
Cannot run a query with hydra namespace

### ISSUE THREAD

**Issue by tpluscode** [dydra/support#55]
As weird as this is, I cannot run any query which contains hydra terms (`http://www.w3.org/ns/hydra/core#` base URI).

Any such query, as simple as 

```
SELECT *
WHERE {
  ?x <http://www.w3.org/ns/hydra/core#member> ?m
}
```

Fails with a message similar to 

```
Invalid message received : \
  Condition: While processing, an error was signaled: \
  Invalid vocabulary term: 'http://www.w3.org/ns/hydra/core#member'.
failed to parse after 'http://www.w3.org/ns/hydra/core#member' \
  at offset N on line M.
```

If I change anything about the Hydra URL or prefix it execs fine. What is special about it?

**Comment by lisp** [comment]
this happens when a term appears which is not present in the version a standard vocabulary which we use internally. where one evolves beyond the version which we have deployed, this will happen.

which hydra vocabulary version do you use?

**Comment by tpluscode** [comment]
Hydra is not versioned really so it's to answer that question. 

That said, `hydra:member` has been in the vocabulary for a very long time.

**Comment by tpluscode** [comment]
Oh wait, if I change the URL to `https` it actually stops complaining.

You have the wrong on your end maybe? `s/https/http`?

**Comment by dydra** [comment]
i believe that the last time we did work related to hydra was years ago and
i may have imported just a small profile.
the protocol should remain http.
i will look at the vocabulary which is in place.

Tomasz Pluskiewicz <notifications@github.com> schrieb am Mi., 22. Mai 2019,
16:54:

**Comment by lisp** [comment]
i have now looked at what appears to be hydra documentation and am reminded of why i did not attempt to incorporate a complete vocabulary. i am not convinced that i can find one.
the namespace document comprises different terms than other documents and there is no way to know which are correct and/or intended to be stable.

what is your exact source?
is it here:

    https://www.w3.org/ns/hydra/core

?

**Comment by lisp** [comment]
i have revised the vocabulary to reflect the document, above.
please advise if it resolves the issue.

**Comment by tpluscode** [comment]
Yes, that is the official source. 
The query now run fine. Thanks you!

By the way, is this process in any way automated? The Hydra vocabulary will change every now and then. In the less-likely event of new terms added, they will not be immediately usable in Dydra, correct?

**Comment by lisp** [comment]
the adaptation process is not automated. some vocabularies are ingestible, but the sources may be json(-ld) or turtle or rdf and in most cases some terms will have been used internally, which means it is possible that source code would need to be adjusted. as almost all vocabularies are stable, it has not been worthwhile to automate the process.
in terms of effect, the error of the sort which you observed occurs often enough with stable vocabularies, that checks for invalid terms are the default service configuration.
