### ISSUE TITLE
Broken filtering inside optional

### ISSUE THREAD

**Issue by knoan** [dydra/support#57]
The following query fails with a generic error message (`Query Execution Failed / An error was encountered`) on any repository:

```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select * where {

     optional { ?0 rdfs:label ?label filter (?label = 'expected') }

}
```

The issue seems related to the use of the `=` operator inside `optional`: works as expected if `optional` is removed or `=` replaced with `!=`.

**Comment by lisp** [comment]
please identify a specific repository and a time in order that it is possible to examine the actual request. the described error does not reproduce in isolation for that given query.

**Comment by knoan** [comment]
https://dydra.com/metreeca/birt, right now. 

I created a view with the query @ https://dydra.com/metreeca/birt/issue-57.html

**Comment by knoan** [comment]
As far as I can see the behaviour is reproducible: I just ran the query a new empty test repository and got the same error message (https://dydra.com/metreeca/test/issue-57.html)

**Comment by lisp** [comment]
for the record,
- the message is more specific than "Query Execution Failed / An error was encountered". it continued with "an error was signaled: Expression compilation failed :
Condition: undefined variable: ?::|label|"
- a report of a query failure which sites the html presentation link for a view will reveal little information about the failure. if one leaves off the ".html" in the link, the response with the error message is available in the browser.

**Comment by lisp** [comment]
the '=' operator should now behave as expected in filters.

**Comment by knoan** [comment]
Everything in working order. Thanks
