### ISSUE TITLE
Cannot load :BaseKB sample data

### ISSUE THREAD

**Issue by paulhoule** [dydra/support#8]
I have a sample data set that I am trying to load into Dydra here:

https://bakemono-public.s3.amazonaws.com/part-r-00000.nt.gz

So far I have run into various problems.

First,  Dydra does not accept the gzip encoding,  which is highly effective on this data.  I cut out 500k facts,  decompressed them,  and attempted to load from

https://bakemono-public.s3.amazonaws.com/tiny.nt

but I got some error message that looked as if it was expecting to get an XML file.

So I try the option of uploading from my computer and I had great luck uploading 5k facts,  but with 50k facts Dydra got stuck on the "Please wait" spinner even though the upload was complete long ago.

Before you get worried I'm going to load the 209 other shards,  I am just looking to see if my output works for you.  I can easily create "blockworlds" from this data about subjects like volcanos or ski areas or navy ships if you pass compatibility testing.

It seems to me that the input from the URL above should "just work".

**Comment by lisp** [comment]
closing, as we've heard nothing more about this. if something more appears, let us know.
